# Generated by Django 4.0.4 on 2022-06-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='contato',
            field=models.CharField(max_length=50),
        ),
    ]
