# Generated by Django 4.0.4 on 2022-04-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
        ('usuario', '0002_usuarios_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='bio',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='idContato',
            field=models.ManyToManyField(to='plataforma.contatos'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='idEndereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.enderecos'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='idPropostas',
            field=models.ManyToManyField(to='plataforma.propostas'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='idTrabalhos',
            field=models.ManyToManyField(to='plataforma.trabalhos'),
        ),
    ]
