# Generated by Django 4.0.4 on 2022-05-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuarios_bio_usuarios_idcontato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='idContato',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='idEndereco',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='idPropostas',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='idTrabalhos',
        ),
    ]
