# Generated by Django 4.0.4 on 2022-06-04 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('usuario', '0004_remove_usuarios_idcontato_remove_usuarios_idendereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contato_fk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='endereco.contatos'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='endereco_fk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='endereco.enderecos'),
        ),
    ]
