# Generated by Django 4.0.4 on 2022-06-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('usuario', '0005_usuarios_contato_fk_usuarios_endereco_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contato_fk',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.contatos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='endereco_fk',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.enderecos'),
        ),
    ]
