# Generated by Django 4.0.4 on 2022-06-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuarios_contato_fk_alter_usuarios_endereco_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media/usuarios/'),
        ),
    ]
