# Generated by Django 4.0.4 on 2022-04-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, null=b'I00\n')),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Propostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=2)),
                ('observacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_serv', models.CharField(max_length=20)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.categorias')),
            ],
        ),
    ]
