# Generated by Django 4.0.4 on 2022-04-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_trabalhos_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhos',
            name='trabEndereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.enderecos'),
        ),
    ]
