# Generated by Django 4.0.4 on 2022-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_trabalhos_trabendereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='cep',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
