# Generated by Django 4.0.4 on 2022-04-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_alter_enderecos_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhos',
            name='trabCateg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.categorias'),
        ),
    ]
