# Generated by Django 4.0.4 on 2022-05-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuarios_idcontato_remove_usuarios_idendereco_and_more'),
        ('plataforma', '0005_trabalhos_trabcateg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, null=True)),
                ('descricao', models.CharField(max_length=30)),
                ('pedCateg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.categorias')),
                ('pedEndereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.enderecos')),
            ],
        ),
        migrations.DeleteModel(
            name='Trabalhos',
        ),
    ]
