# Generated by Django 4.0.4 on 2022-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_pedidos_peduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
