# Generated by Django 4.0.4 on 2022-05-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_pedidos_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='imagem',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='imagem',
            field=models.ManyToManyField(blank=True, null=True, to='plataforma.imagem'),
        ),
    ]
