# Generated by Django 4.0.4 on 2022-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_imagem_remove_pedidos_imagem_pedidos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='imagem',
            field=models.ManyToManyField(blank=True, to='plataforma.imagem'),
        ),
    ]
