# Generated by Django 4.0.4 on 2022-05-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_alter_imagem_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='imagem',
            new_name='pedImagem',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='./media'),
        ),
    ]
