# Generated by Django 4.0.4 on 2022-05-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_rename_imagem_pedidos_pedimagem_alter_imagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedImagem',
            field=models.ManyToManyField(blank=True, related_name='pedidos', to='plataforma.imagem'),
        ),
    ]
