# Generated by Django 4.0.4 on 2022-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_alter_imagem_imagem_alter_pedidos_pedimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='pedImagem',
            field=models.ManyToManyField(blank=True, to='plataforma.imagem'),
        ),
    ]
