# Generated by Django 4.0.4 on 2022-05-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_alter_pedidos_pedimagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='pedCateg',
            new_name='categoria_fk',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='pedEndereco',
            new_name='endereco_fk',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='pedUser',
            new_name='usuario_fk',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='pedImagem',
        ),
        migrations.AddField(
            model_name='imagem',
            name='pedido_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.pedidos'),
        ),
    ]
