# Generated by Django 4.0.4 on 2022-05-14 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0015_rename_pedcateg_pedidos_categoria_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
