# Generated by Django 4.0.4 on 2022-05-14 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0016_propostas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='pedido_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pedidos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='categoria_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.categorias'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='endereco_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.enderecos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propostas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
