# Generated by Django 4.0.4 on 2022-05-23 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0017_alter_enderecos_cep_alter_imagem_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=50)),
                ('dataenvio', models.DateTimeField()),
                ('userDest_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('userRem_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
