# Generated by Django 4.0.4 on 2022-05-29 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0018_mensagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propostas',
            name='usuario',
        ),
        migrations.AddField(
            model_name='propostas',
            name='pedido_fk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pedido_fk', to='plataforma.pedidos'),
        ),
        migrations.AddField(
            model_name='propostas',
            name='usuarioPedido_fk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuarioPedido_fk', to='plataforma.pedidos'),
        ),
        migrations.AddField(
            model_name='propostas',
            name='usuarioProposta_fk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuarioProposta_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propostas',
            name='observacao',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
