# Generated by Django 4.0.4 on 2022-05-29 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0020_remove_propostas_usuariopedido_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='prevInicio',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
