# Generated by Django 4.0.4 on 2022-06-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0022_delete_contatos_alter_pedidos_endereco_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='propostaAceita',
            field=models.BooleanField(null=True),
        ),
    ]
